/**
 * Every value below is interpolated into YAML, into a git ref name, and into a
 * hostname. A newline would let a caller inject a sibling top-level key beside
 * `staging:` — including a `publish:` block, which targets the production site.
 * The guard is here, rather than relying on the digits check in validate.mjs,
 * because that one guards the artifact's self-reported field, not these arguments.
 */
function assertPr(pr) {
  if (!/^\d+$/.test(String(pr))) {
    throw new TypeError(
      `preview PR number must be digits only, got ${JSON.stringify(pr)}`,
    );
  }
  return String(pr);
}

export const previewBranch = (pr) => `preview/pr${assertPr(pr)}-staging`;
export const previewUrl = (pr) => `https://magpie-pr${assertPr(pr)}.staged.apache.org/`;

/**
 * Generated by the publisher, never taken from the artifact: an .asf.yaml
 * shipped by a pull request could name a different profile or a publish block.
 */
export function renderAsfYaml(pr) {
  const n = assertPr(pr);
  return `# Generated by preview-publish. Do not edit.
# Serves this branch at ${previewUrl(pr)}
staging:
  profile: pr${n}
  whoami: ${previewBranch(pr)}
`;
}

export function renderRobots() {
  return `User-agent: *
Disallow: /
`;
}

/**
 * Deleting a branch does not unstage the site, so a retired preview is
 * overwritten with this before its branch is deleted.
 */
export function renderTombstone({ pr, repo }) {
  const n = assertPr(pr);
  const url = `https://github.com/${repo}/pull/${n}`;
  return `<!doctype html>
<meta charset="utf-8">
<meta name="robots" content="noindex">
<title>Preview retired — PR #${n}</title>
<h1>This preview has been retired</h1>
<p>The preview for pull request #${n} is no longer published, because the
pull request is closed or is no longer armed for previews.</p>
<p><a href="${url}">${url}</a></p>
`;
}
