// Short directory descriptions; implementation details remain in each tool's docs.
export const toolSummaries: Record<string, string> = {
  'agent-guard': 'Checks shell commands against deterministic rules before the agent runs them.',
  'agent-isolation': 'Provides the scripts and configuration used to set up an isolated agent workspace.',
  'apache-projects': 'Reads public Apache project information, committee rosters, and committer records.',
  'asf-svn': 'Connects Magpie workflows to Apache’s Subversion repositories.',
  'bitbucket': 'Connects Magpie to Bitbucket repositories and pull requests.',
  'change-request': 'Defines the interface for reviewing and merging changes across different backends.',
  'cve-org': 'Submits allocated CVE records to CVE.org for publication.',
  'cve-tool': 'Defines the interface for CVE allocation and record management.',
  'cve-tool-vulnogram': 'Allocates CVE IDs and publishes records through Apache’s Vulnogram instance.',
  'dashboard-generator': 'Generates issue dashboards that can be refreshed and published by CI.',
  'dev': 'Checks framework placeholders and supplies agent pre-commit helpers.',
  'egress-gateway': 'Restricts outbound HTTP connections to an approved list of hosts.',
  'forwarder-relay': 'Defines how to recognize forwarded security reports and preserve reporter credit.',
  'fossil': 'Connects Magpie to Fossil repositories, tickets, wikis, and forums.',
  'github': 'Reads and updates GitHub issues, pull requests, project boards, and repositories.',
  'github-body-field': 'Reads or updates one issue-body field without loading the whole issue into the agent.',
  'github-rollup': 'Updates an issue’s status summary without loading the existing summary into the agent.',
  'gmail': 'Reads Gmail threads and prepares drafts; it does not send messages.',
  'jira': 'Connects issue workflows to Jira trackers.',
  'jira-patch': 'Supports code review through patches attached to Jira issues.',
  'mail-archive': 'Defines the interface for reading public mailing-list archives.',
  'mail-patch': 'Supports code review through patches exchanged on a mailing list.',
  'mail-source': 'Defines a shared message format for importing reports from different mail backends.',
  'maildir': 'Reads and writes local Maildir and mbox files without a cloud mail account.',
  'permission-audit': 'Audits and updates Claude Code permission entries in project settings.',
  'pilot-report-validator': 'Checks that experimental-workflow pilot reports contain the required information.',
  'ponymail': 'Reads Apache mailing-list archives to cross-reference public discussions.',
  'pr-management-stats': 'Collects and classifies data for pull-request statistics.',
  'preflight-audit': 'Tests bulk-workflow classification rules against real or recorded tracker data.',
  'privacy-llm': 'Detects and redacts personal information before content reaches an external model.',
  'probe-templates': 'Provides reusable scripts for testing related failure scenarios when reproducing an issue.',
  'sandbox-lint': 'Checks Claude Code sandbox settings against Magpie’s baseline and security requirements.',
  'scan-format': 'Defines how security workflows read findings from different scanner formats.',
  'security-tracker-stats-dashboard': 'Builds an HTML dashboard of security-report progress and backlog.',
  'skill-and-tool-validator': 'Checks skill metadata, internal links, and placeholder conventions.',
  'skill-evals': 'Tests skill behavior against example cases and expected structured outputs.',
  'skill-reconciler-diff': 'Compares two sets of skill files and reports structural changes.',
  'skill-token-count': 'Measures skill token counts and checks the published measurements.',
  'sourcehut': 'Connects Magpie to SourceHut tickets, patch reviews, builds, and repositories.',
  'spec-inventory': 'Indexes repository information for the specification-driven development loop.',
  'spec-loop': 'Runs development iterations against a specification with human approval points.',
  'spec-status-index': 'Groups development specifications by status to identify the next work item.',
  'spec-validator': 'Checks development specification files against the framework’s format.',
  'symlink-lint': 'Checks that framework skill symlinks are wired correctly.',
  'vcs': 'Provides common version-control operations through a shared interface.',
  'vendor-neutrality-score': 'Measures vendor neutrality from the framework’s tool and skill metadata.',
  'vetted-ops': 'Runs a defined set of policy-scoped forge operations through one dispatcher.',
};
