// An illustrative report, using the documented Magpie security procedures.
// These are narrative milestones, not a replacement for the full process.
export const securityStory = [
  { label: "Report", kind: "report", prompt: "Investigate this private security report.", skill: "security-issue-import", artifact: "Private report", title: "An archive can write outside its folder.", rows: [["Reported input", "../../outside.txt"], ["Expected behaviour", "Files stay inside the extraction folder"], ["Evidence captured", "Reproducer · affected versions · reporter thread"]], result: "The report and evidence are ready to investigate.", handoff: "You approve creating the private tracker." },
  { label: "Triage", kind: "triage", prompt: "Is this a vulnerability? Check our history.", skill: "security-issue-triage", artifact: "Triage decision", title: "A real vulnerability. A different code path.", rows: [["Security model", "Crosses the archive extraction trust boundary"], ["Previous reports", "Related issue found; not a duplicate"], ["Recommendation", "Accept the report and prepare a fix"]], result: "Evidence, tracker update, and reporter reply prepared.", handoff: "Your security team confirms the decision and sends the reply." },
  { label: "Fix & test", kind: "fix", prompt: "Fix it and prove the bug cannot come back.", skill: "security-issue-fix", artifact: "Patch + regression test", title: "The test fails before the fix. Passes after.", rows: [["− Before", "Archive member escapes the extraction folder"], ["+ After", "Unsafe paths rejected before writing"], ["✓ Regression test", "Traversal attempt blocked · valid archive still extracts"]], result: "Patch, test evidence, and fix PR ready for review.", handoff: "You approve the PR. A maintainer reviews and merges it." },
  { label: "Release", kind: "release", prompt: "Is the fix available to our users yet?", skill: "security-issue-sync", artifact: "Release check", title: "Keep disclosure tied to the fixed release.", rows: [["Fix", "Merged and linked to the report"], ["Fixed version", "Confirmed in the public release"], ["CVE record", "Affected versions, severity, and credit checked"]], result: "The release manager gets a complete disclosure handoff.", handoff: "The release manager confirms the fixed release is available." },
  { label: "Disclose", kind: "advisory", prompt: "Prepare the advisory and CVE record.", skill: "security-issue-sync", artifact: "Advisory draft", title: "Tell users what happened and how to update.", rows: [["Impact", "Archive path traversal"], ["Action", "Upgrade to the fixed release"], ["Included", "Affected versions · fix link · reporter credit"]], result: "Advisory and CVE details prepared from the same evidence.", handoff: "A person reviews and sends the advisory." },
  { label: "Close", kind: "closed", prompt: "Close the report and keep what we learned.", skill: "security-issue-sync + security-model-update", artifact: "Report resolved", title: "Fixed. Released. Disclosed.", rows: [["Public record", "Advisory and CVE linked"], ["Tracker", "Closed after confirmation"], ["Next report", "Security model updated with the lesson"]], result: "No loose ends for the maintainer to chase.", handoff: "You confirm publication, closure, and the model update." },
];
