import { useState } from "react";
import { Check, GitPullRequest, ShieldCheck, Inbox, PackageCheck, FileText } from "lucide-react";
import { withBase } from "@/ui/lib/utils";

const workflows = [
  { id: "security", label: "Security reports", icon: ShieldCheck, title: "From first report to a considered response.", text: "Check the history, assess the report, and prepare a response. Keep the sensitive details private and the next decision clear.", path: "/docs/security/readme", command: "Triage the new security reports", items: ["Checked the project’s security model", "Compared with previous reports", "Prepared a response for your review"], file: "Response draft", body: "The report is ready for review. The assessment, supporting evidence, and proposed next steps are attached.", action: "Review the assessment", tag: "Private workspace" },
  { id: "reviews", label: "Pull requests", icon: GitPullRequest, title: "Find the reviews that need your attention.", text: "Understand what changed, spot missing context, and work through the queue with a prepared review in front of you.", path: "/docs/pr-management/readme", command: "Help me work through the PR queue", items: ["Grouped incoming changes by area", "Checked tests and project conventions", "Drafted review notes with file references"], file: "Review notes", body: "The change is scoped and the tests pass. One edge case needs a closer look; the relevant code and a suggested test are included.", action: "Review the changes", tag: "Your repository" },
  { id: "issues", label: "Issue triage", icon: Inbox, title: "Turn a busy backlog into useful next steps.", text: "Find duplicates, reproduce reported bugs, and prepare a well-scoped fix. Give good reports the attention they deserve.", path: "/docs/issue-management/readme", command: "Triage the new issues", items: ["Checked for duplicates and related fixes", "Reproduced the reported behaviour", "Prepared a proposed disposition"], file: "Triage summary", body: "The bug is reproducible on the current branch. A regression test and a proposed fix are ready for a maintainer to review.", action: "Read the findings", tag: "Your issue tracker" },
  { id: "releases", label: "Releases", icon: PackageCheck, title: "Keep the release moving with less chasing.", text: "Prepare the release plan, follow the checklist, and draft announcements. Signing and publishing stay with your team.", path: "/docs/release-management/readme", command: "Prepare the next release", items: ["Collected changes since the last release", "Prepared the release checklist", "Drafted the announcement"], file: "Release checklist", body: "The release plan is ready. Review the candidate, sign the artifacts, and approve the announcement when your project is ready.", action: "Review the release plan", tag: "ASF release workflow" },
];
export default function WorkflowExplorer() {
  const [selected, setSelected] = useState(0);
  const w = workflows[selected];
  const choose = (index: number) => { setSelected(index); document.getElementById(`workflow-tab-${index}`)?.focus(); };
  return <div className="workflow-explorer">
    <div role="tablist" aria-label="Maintainer workflows" className="workflow-tabs">{workflows.map((item, i) => <button key={item.id} id={`workflow-tab-${i}`} role="tab" aria-selected={selected === i} aria-controls="workflow-panel" tabIndex={selected === i ? 0 : -1} onClick={() => setSelected(i)} onKeyDown={event => { if (["ArrowRight", "ArrowLeft", "Home", "End"].includes(event.key)) { event.preventDefault(); choose(event.key === "Home" ? 0 : event.key === "End" ? workflows.length - 1 : (i + (event.key === "ArrowRight" ? 1 : -1) + workflows.length) % workflows.length); } }}><item.icon size={18} />{item.label}</button>)}</div>
    <div role="tabpanel" id="workflow-panel" aria-labelledby={`workflow-tab-${selected}`} tabIndex={0} className="workflow-panel">
      <div className="workflow-description" key={`${w.id}-text`}><h3>{w.title}</h3><p>{w.text}</p><a className="text-link" href={withBase(w.path)} target="_blank" rel="noreferrer">Explore this workflow </a></div>
      <div className="workflow-preview" key={w.id}><div className="preview-top"><span>{w.tag}</span><span>Example</span></div><div className="preview-body"><div className="prompt-line"><span className="prompt-caret">›</span>{w.command}</div><ul>{w.items.map(item => <li key={item}><Check size={14} />{item}</li>)}</ul><div className="draft-preview"><div><FileText size={15} /><strong>{w.file}</strong><span>Draft</span></div><p>{w.body}</p><a href={withBase(w.path)}>{w.action}</a></div></div><div className="preview-bottom">Awaiting maintainer review</div></div>
    </div>
  </div>;
}
