// Illustrative transcripts, based on docs/security/process.md and the live demo.
// Human approvals and external release events are explicit, not automated away.
export const securityStages = [
  { label: "Set up", prompt: "Set up Magpie for this project.",
    steps: [["Detect", "Repository, tracker, and security list", "Read project configuration and available tools."], ["Configure", "Project-specific workflows", "Prepared local settings for security intake, fixes, and releases."], ["Check", "Required configuration", "Found the remaining setup steps before handling private reports."]],
    result: "Your agent now knows the project’s tools and conventions.", approval: "Confirm the local configuration before applying it." },
  { label: "Isolate & protect", prompt: "Isolate the agent and protect private report data.",
    steps: [["Sandbox", "Limit files and commands", "Prepared an isolated workspace and action-guard configuration."], ["Privacy", "Check approved models", "Private data fetches are blocked until the model stack is approved."], ["Redact", "Personal data before model access", "Reporter identifiers are replaced; the mapping stays local."]],
    result: "The environment is prepared for confidential work.", approval: "Approve the sandbox and privacy configuration." },
  { label: "Model the project", prompt: "Prepare our security model.",
    steps: [["Read", "Code, documentation, and past advisories", "Identified exposed surfaces and trust boundaries."], ["Draft", "What counts as a vulnerability", "Recorded in-scope threats and known out-of-scope behaviour."], ["Prepare", "Security-model update", "A reviewable change to the project’s security documentation."]],
    result: "New reports can be assessed against your project’s own rules.", approval: "Review the model before adopting it." },
  { label: "Import reports", prompt: "Sync the security reports received in the last two days.",
    steps: [["Fetch", "Unimported report threads", "Found an archive traversal report and a latency complaint."], ["Classify", "Reports, scanner noise, and duplicates", "Extracted affected versions, evidence, and reporter details."], ["Prepare", "Trackers and receipt drafts", "Private report contents stay on the private tracker."]],
    result: "Incoming mail is ready to become structured, tracked work.", approval: "Confirm tracker creation. Review and send the receipt drafts." },
  { label: "Triage & discuss", prompt: "Assess the reports and check the project’s history.",
    steps: [["Compare", "Security model and prior reports", "Traversal crosses a trust boundary; it is not a duplicate."], ["Propose", "Disposition and next actions", "Accept the traversal report. Latency has no security impact."], ["Coordinate", "Team discussion and reporter replies", "Drafted the triage proposal, reviewer mentions, and responses."]],
    result: "Valid reports advance; invalid reports get a reasoned reply. Stalled discussions can be escalated.", approval: "The security team decides validity and approves outward actions." },
  { label: "Allocate a CVE", prompt: "Prepare CVE allocation for the accepted report.",
    steps: [["Prepare", "CVE allocation request", "Collected the product, affected scope, and issue summary."], ["Link", "Allocated identifier and tracker", "After allocation: attach CVE-2026-XXXXX to the issue."], ["Sync", "Labels, record link, and CVE JSON", "Prepared the tracker update and remediation handoff."]],
    result: "The report, CVE record, and remediation work stay connected.", approval: "The authorised maintainer confirms allocation and tracker updates." },
  { label: "Fix & test", prompt: "Implement a fix and regression test for the accepted report.",
    steps: [["Reproduce", "Archive member path traversal", "The regression test demonstrates the reported behaviour."], ["Patch", "Normalise paths before extraction", "The regression test and related tests pass with the fix."], ["Prepare", "Fix PR and tracker link", "Use the project’s disclosure policy; keep sensitive details out of public text."]],
    result: "A tested fix is ready for code review, with the tracker kept in sync.", approval: "You approve opening the PR. A maintainer reviews and merges it." },
  { label: "Coordinate release", prompt: "Check whether the fix is ready for disclosure.",
    steps: [["Sync", "Merged fix and released version", "Wait until the fix is available in a public release."], ["Validate", "Affected versions, severity, and credit", "Check every required CVE field and the public summary."], ["Prepare", "Release-manager handoff", "Push the review-ready record and prepare the advisory handoff after approval."]],
    result: "The disclosure package is ready when the fixed release is available.", approval: "The release manager confirms readiness and reviews the advisory." },
  { label: "Publish advisory", prompt: "Prepare disclosure for the released fix.",
    steps: [["Draft", "Advisory from the record and fix", "Include impact, affected versions, upgrade advice, and reporter credit."], ["Review", "CVE record and advisory email", "Resolve review comments and confirm the publish-ready record."], ["Wait", "Human sends the advisory", "The release manager sends it; the public archive URL becomes the next input."]],
    result: "Users receive a complete advisory with a released fix to upgrade to.", approval: "A person reviews and sends the advisory. Magpie never sends it silently." },
  { label: "Close & learn", prompt: "Sync the public advisory and close out the report.",
    steps: [["Capture", "Public advisory archive URL", "Attach the published advisory and regenerate the CVE JSON."], ["Publish", "CVE record and tracker close-out", "On confirmation: publish the record, close the issue, and archive the board item."], ["Learn", "Security model and reporter credit", "Propose lessons for the security model; support credit corrections."]],
    result: "One report becomes a tested fix, a release, a public CVE, and a closed tracker.", approval: "Confirm publication and closure; the release manager verifies the result." },
];
